# 2.1. 数据操作
## 2.1.1. 构造

In [40]:
import torch

In [41]:
# 创建一个行向量 x
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
# 访问张量的 形状 （沿每个轴的长度）
x.shape

torch.Size([12])

In [43]:
# 张量中元素的总数
x.numel()

12

In [44]:
# 改变一个张量的形状而不改变元素数量和元素值，我们可以调用 reshape 函数
reshape = x.reshape(3,4)
print(reshape)

# 使用 -1 来自动计算张量的行列值
reshape = x.reshape(-1,4)
print(reshape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [45]:
# 创建全是 0 的张量
zeros = torch.zeros((2,3,4))
print(zeros)

# 创建全是 1 的张量
ones = torch.ones(2,3,4)
print(ones)

# 创建 随机数 的张量
randn = torch.randn(3,4)
print(randn)

# 创建张量的时候，确定值
tensor = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print(tensor)



tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[-0.8616,  0.9306,  0.2863,  1.1673],
        [-0.6682,  0.5040,  0.3853, -1.7615],
        [ 0.9356, -0.6111,  0.3818,  1.1660]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


## 2.1.2. 运算

In [46]:
# 对于任意具有相同形状的张量,按元素计算
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])

x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [47]:
# 求幂运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [48]:
# 张量的 连接, 0是行，1是列。
X = torch.arange(12,dtype=torch.float32).view(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(X)
print(Y)
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [49]:
# 张量的 相等 运算

X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
# 张量的内置函数， 内和
X.sum()

tensor(66.)

## 2.1.3. 广播机制

In [51]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print("a",a)
print("b",b)
print("a+b",a+b)


a tensor([[0],
        [1],
        [2]])
b tensor([[0, 1]])
a+b tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 2.1.4. 索引和切片 (访问)

In [52]:
# 倒数第一行
print(X[-1])

# 第1至第3行
print(X[1:3])

# 赋值
X[1,2] = 9
print(X)

# 范围选择,0-2行，所有列
print(X[0:2,:])



tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[0., 1., 2., 3.],
        [4., 5., 9., 7.]])


## 2.1.5. 节省内存

In [53]:
# 重新分配内存
before = id(Y)
Y = Y + X
print(id(Y)==before)


False


In [54]:
# 原地操作，直接修改原有内存，(节约内存)
before = id(X)
X += Y
print(id(X)==before)


True


## 2.1.6. 转换为其他 Python 对象

In [55]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [56]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)