# 2.3. 线性代数
## 2.3.1. 标量

In [2]:
import torch
# 实例化两个标量 , 并进行四则运算
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 2.3.2. 向量

In [3]:
# 创建一维张量
x = torch.arange(4)
print(x)

# 访问元素
x[3]

tensor([0, 1, 2, 3])


tensor(3)

## 2.3.2.1. 长度、维度和形状

In [4]:
# 访问张量的长度
print(len(x))

# 张量的形状，指的是张量每个轴的长度，即每个轴的元素个数。
print(x.shape)

4
torch.Size([4])


## 2.3.3. 矩阵

In [5]:
# 实例化矩阵 , reshape, resize, view
reshape = torch.arange(20).reshape(5,4)
resize = torch.arange(20).resize(5,4)
view = torch.arange(20).view(5,4)
reshape,resize,view

C:\ProgramData\Miniconda3\envs\d2l_learning\lib\site-packages\torch\tensor.py:474: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [6]:
# 矩阵的转置
print(view.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [7]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print('B ==> ',B)
print('B.T ==> ',B.T)
print('B == B.T ==> ',B == B.T)

B ==>  tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
B.T ==>  tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
B == B.T ==>  tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## 2.3.4. 广义的张量

In [8]:
# 一阶张量的特殊叫法为 向量
# 一阶张量的特殊叫法为 矩阵
# 具有2、3、4轴的张量，统称为张量
X = torch.arange(24).reshape(2, 3, 4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


## 2.3.5. 张量算法的基本性质


In [9]:
# 两个相同形状的矩阵相加会在这两个矩阵上执行元素加法
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print('A ==> ',A)
print('B ==> ',B)
print('A+B ==> ',A+B)

A ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
B ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
A+B ==>  tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [10]:
# 两个矩阵的按元素乘法称为 哈达玛积
print('A ==> ',A)
print('B ==> ',B)
print('A ⊙ B ==> ',A * B)

A ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
B ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
A ⊙ B ==>  tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [11]:
# 张量乘以或加上一个标量不会改变张量的形状
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print('a + X ==> ',a + X)
print('(a * X).shape ==> ',(a + X).shape)

a + X ==>  tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
(a * X).shape ==>  torch.Size([2, 3, 4])


## 2.3.6. 张量的汇总(sum)


In [12]:
# 默认情况下，调用求和函数会将一个张量在所有轴上汇总为一个标量,
# 无论是几阶张量，都最终汇总成一个数字。
x = torch.arange(4, dtype=torch.float32)
print('x ==> ',x)
print('x.sum() ==> ',x.sum())

x ==>  tensor([0., 1., 2., 3.])
x.sum() ==>  tensor(6.)


In [13]:
# 按轴汇总，输入哪个轴，哪个轴就会丢失维度

# 输入矩阵沿0轴汇总以生成输出向量，因此输入的轴0的维数在输出形状中丢失
A_sum_axis0 = A.sum(axis=0)
print('A_sum_axis0 ==> ',A_sum_axis0)
print('A_sum_axis0.shape ==> ',A_sum_axis0.shape)

A_sum_axis0 ==>  tensor([40., 45., 50., 55.])
A_sum_axis0.shape ==>  torch.Size([4])


In [14]:
# 输入矩阵沿0轴汇总以生成输出向量，因此输入的轴0的维数在输出形状中丢失
A_sum_axis1 = A.sum(axis=1)
print('A_sum_axis1 ==> ',A_sum_axis1)
print('A_sum_axis1.shape ==> ',A_sum_axis1.shape)

A_sum_axis1 ==>  tensor([ 6., 22., 38., 54., 70.])
A_sum_axis1.shape ==>  torch.Size([5])


In [15]:
# 2阶，张量，按照2个轴汇总，最后丢失所有维度。
A.sum(axis=[0, 1])

tensor(190.)

In [16]:
# 计算任意形状张量的平均值
print('A.mean() ==> ',A.mean())
print('A.sum() / A.numel() ==> ',A.sum() / A.numel())

A.mean() ==>  tensor(9.5000)
A.sum() / A.numel() ==>  tensor(9.5000)


In [17]:
# 按照某一个轴求均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 2.3.6.1. 非汇总求和

In [18]:
# 汇总的时候，也可以不丢维度。
sum_A = A.sum(axis=1, keepdims=True)
print('A  ==> ', A)
print('sum_A  ==> ', sum_A)

A  ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
sum_A  ==>  tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [19]:
# 由于 sum_A 在对每行进行求和后仍保持两个轴，我们可以通过广播将 A 除以 sum_A
print('A ==> ',A)
print('A / sum_A  ==> ', A / sum_A)

A ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
A / sum_A  ==>  tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [20]:
# 按照某一个轴逐渐累计。
print('A ==> ',A)
A.cumsum(axis=0)

A ==>  tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 2.3.7. 点积（Dot Product

In [22]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [24]:
torch.sum(x * y)

tensor(6.)

## 2.3.8. 矩阵-向量积

In [26]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 2.3.9. 矩阵-矩阵乘法

In [27]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 2.3.10. 范数

In [29]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [31]:
torch.abs(u).sum()

tensor(7.)

In [ ]:
torch.norm(torch.ones((4, 9)))