# 2.5. 自动求导

假设我们想对函数  y= 2x ⊤ x 关于列向量  x 求导

In [1]:
import torch

# 定义张量，并计算、存储梯度
x = torch.arange(4.0,requires_grad=True)
x.grad
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [2]:
# 求张量的內积 , 2 x (1 + 4 + 9)
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [3]:
# 调用反向传播函数来自动计算y关于x 每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [4]:
# 函数  y=2x⊤x  关于 x  的梯度应为 4x 。让我们快速验证我们想要的梯度是否正确计算
x.grad == 4 * x


tensor([True, True, True, True])