# 3.3 线性回归的简洁实现

## 3.3.1 生成数据集

In [20]:
import d2l.torch
import torch

true_w = torch.Tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.torch.synthetic_data(true_w, true_b, 1000)

## 3.3.2 读取数据集

In [21]:
from torch.utils import data


# 读取方法
def load_array(data_arrays, batch_size, is_train=True):
    """构造一个pytorch数据迭代"""
    dataset = data.TensorDataset(*data_arrays)
    dataloader = data.DataLoader(dataset, batch_size, shuffle=is_train)
    return dataloader


batch_size = 10
data_iter = load_array((features, labels), batch_size)

# 调用
next(iter(data_iter))

[tensor([[ 0.6535,  0.9114],
         [-0.4265, -0.3389],
         [ 0.7408,  0.7629],
         [ 0.3999,  0.9250],
         [-0.6112, -0.4995],
         [ 1.0097,  1.1864],
         [ 1.1125, -1.9490],
         [ 0.3404, -0.1617],
         [-2.5093,  0.1011],
         [ 0.8208,  1.7720]]),
 tensor([[ 2.3969],
         [ 4.5128],
         [ 3.0841],
         [ 1.8528],
         [ 4.6662],
         [ 2.1889],
         [13.0433],
         [ 5.4247],
         [-1.1618],
         [-0.1859]])]

## 3.3.3 定义模型

In [22]:
from torch import nn, tensor

net = nn.Sequential(nn.Linear(2, 1))

## 3.3.4 初始化模型参数

In [29]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

tensor([0.])

## 3.3.5 定义损失函数

In [30]:
loss = nn.MSELoss

## 3.3.6 定义优化算法

In [31]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

## 3.3.7 训练

In [32]:
num_epochs = 3

for num_epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {num_epoch + 1}, loss {l:f}')

RuntimeError: Boolean value of Tensor with more than one value is ambiguous